import type {Metadata} from "next";
import {Geist, Geist_Mono, Recursive} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";

const recursive = Recursive({subsets: ['latin']})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${recursive.className} ${geistMono.variable} antialiased`}
        >
        <Navbar></Navbar>
        <main className={"grainy-light flex flex-col min-h-[calc(100vh-3.5rem-1px)]"} style={{minHeight: "calc(100vh - 14rem)"}}>
            <div className={"flex-1 flex flex-col h-full"}>
                <Providers>{children}</Providers>
            </div>
            <Footer></Footer>
        </main>
        </body>
        </html>
    );
}
